---
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE, message=FALSE)
```

```{r}
library(tidyr)
library(patchwork)
library(dplyr)
library(ggplot2)
library(Seurat)
library(DT)
library(ComplexHeatmap)
library(circlize)
library(tibble)
library(OrgHeatmap)
library(ggrepel)
library(scales)



WORK_DIR <- '/home/chenshuting/drug_toxicity/pan_tissue_landscape/'
DATA_DIR <- '/home/chenshuting/drug_toxicity/pan_tissue/'

source('/home/chenshuting/drug_toxicity/Normal_DSS/scripts/plot/visualization.R')


```

# Data reading

```{r}
## Read sample information
sample_info_tissue <- read.csv(paste0(WORK_DIR,'Tables/sample_info_tissue_scPharm.csv'))
sample_info_imm <- read.csv(paste0(WORK_DIR,'Tables/sample_info_imm_scPharm.csv')) 

## Get 295 drug information
drug_info <- readRDS('/home/chenshuting/drug_toxicity/prior_knowledge/drug_info_df.rds')
drug_id_names <- sort(drug_info$drug_id_name)

# Drug-tissue-toxicity metric dataframe
drug_tissuetox_df <- readRDS(paste0(WORK_DIR,'Rdata/drug_tissuetox_df/drug_tissuetox_df.rds')) 
tissues <- unique(drug_tissuetox_df$tissue)
drug_tissuetox_df_ds <- readRDS(paste0(WORK_DIR,'Rdata/drug_tissuetox_df/drug_tissuetox_df_dshbca.rds')) # Generated by 0.1sampling.R
drug_tissuetox_df_imm <- readRDS(paste0(WORK_DIR,'Rdata/drug_tissuetox_df/drug_tissuetox_df_imm.rds'))

# Sample DSE information
sample_tox_df <- readRDS(paste0(WORK_DIR,'Rdata/sample_tox_df/sample_tox_df.rds'))
sample_tox_df_ds <- readRDS(paste0(WORK_DIR,'Rdata/sample_tox_df/sample_tox_df_dshbca.rds'))
sample_tox_df_imm <- readRDS(paste0(WORK_DIR,'Rdata/sample_tox_df/sample_tox_df_imm.rds'))
sample_tox_list     <- split(sample_tox_df,     sample_tox_df$tissue)

## Read sample information
sample_info_tissue <- read.csv(paste0(WORK_DIR,'Tables/sample_info_tissue_scPharm.csv'))
sample_info_list    <- split(sample_info_tissue, sample_info_tissue$Tissue)

```


# overall

## F1A Dataset statistics

```{r}
# Rename Num_cells
tissue_df <- sample_info_tissue %>%
  dplyr::rename(tissue_num_cells = Num_cells) 
imm_df <- sample_info_imm %>%
  dplyr::rename(imm_num_cells = Num_cells) 

# Merge
sample_info <- full_join(tissue_df, imm_df, by = c('Tissue','Project',"Sample",'cohort')) 

sample_info <- sample_info %>%
  mutate(
    ## Treat NA as 0 first (avoid logical errors)
    tissue_num_cells = ifelse(is.na(tissue_num_cells), 0, tissue_num_cells),
    imm_num_cells    = ifelse(is.na(imm_num_cells), 0, imm_num_cells)
  ) %>%
  mutate(
    cell_type = case_when(
      
     Tissue == "Blood" ~ "blood",
     Tissue == "Brain" ~ "brain",
     
     tissue_num_cells > 0 & imm_num_cells > 0 ~ "epi & imm",
      
      tissue_num_cells == 0 & imm_num_cells > 0 ~ "immune",
      
      tissue_num_cells > 0 & imm_num_cells == 0 ~ "epithelial",
    
    )
  )

# Directly merge sample info with rbind
sample_info_tissue$Cell_type <- ifelse(
  sample_info_tissue$Tissue %in% c("Blood", "Brain"),
  sample_info_tissue$Tissue,
  "Epithelial"
)
sample_info_imm$Cell_type <- "Immune"
sample_info_rbind <- rbind(sample_info_tissue,sample_info_imm)

```

```{r}
print(paste0("number of tissues:",length(unique(sample_info$Tissue))))
print(paste0("number of datasets:",length(unique(sample_info$Project))))
print(paste0("number of samples:",length(unique(sample_info$Sample))))
print(paste0("number of tissue cells:",sum(sample_info_tissue$Num_cells)))
print(paste0("number of imm cells:",sum(sample_info_imm$Num_cells)))
print(paste0("number of drugs:",length(unique(sample_tox_df$drug_id_name))))

```


```{r,fig.width=7,fig.height=6}
# Use names(human_organ_coord) to see available organs

# Define mapping to own data tissues
mapping <- c("Bladder"="bladder","Blood"="arm_blood_vessel","Bowel"="large_intestine","Breast"="breast","Head_and_Neck"="nasopharyngeal",
             "Kidney"="kidney","Liver"="liver","Lung"="lung","Pancreas"="pancreas","Prostate"="prostate","Skin"="skin",
             "Uterus"="uterus","Brain"="brain","Esophagus"="esophagus","Pleura"="pleura","Stomach"="stomach",
             "Thyroid"="thyroid_gland","Ovary"="ovary")

# Rename sample_info columns for identification
org_data <- unique(sample_info[,c('Tissue','Project')]) %>%
  dplyr::rename(organ = Tissue) %>%
  dplyr::mutate(value=1)

p <- OrgHeatmap(data=org_data,species="human",aggregate_method="count", # count aggregates by occurrence (dataset count)
           organ_name_mapping=mapping,title = "Number of Datasets",
           organbar_low ="#FFF7BC",
           organbar_high ="#D95F0E",
           save_plot = FALSE) 
f1a <- p$plot +
  plot_annotation(
    tag_levels = list(c("A"))
  )
print(f1a) 
ggsave(paste0(WORK_DIR,"Figures/Figure1_landscape/A_organplot.pdf"),width=7,height=6)

```


## F1B Sample count statistics

```{r,fig.width=6,fig.height=4}
sample_info_rbind$Cell_type <- factor(sample_info_rbind$Cell_type,
                                    levels = c('Epithelial','Immune',"Brain","Blood"))
write.csv(sample_info_rbind,paste0(WORK_DIR,'Tables/supplementary_tables/sample_info.csv'),row.names = F)

f1b <- plot_stacked_bar(
  df = sample_info_rbind,
  x_col = "Tissue",
  y_col = "Sample",
  fill_col = "Cell_type",
  agg_func = n_distinct,
  plot_title = "",
  xlab = "Tissue",
  ylab = "Number of samples",
  fill_legend = "Cell type",
  palette = 'Set3' # Changed color palette
) + theme(legend.position = c(1, 1.1), # Position relative to entire plot
    legend.justification = c(1, 1)) + # Anchor: 1=right, 0=bottom
  plot_annotation(
    tag_levels = list(c("B"))
  )
f1b

ggsave(paste0(WORK_DIR,"Figures/Figure1_landscape/B_samplecount.pdf"),width=6,height=4)

```




## F1C Cell count statistics

```{r,fig.width=6,fig.height=4}

sample_info_tissue$data_panel <- 'epithelial'
sample_info_tissue$data_panel[sample_info_tissue$Tissue=="Blood"] <- "blood"
sample_info_tissue$data_panel[sample_info_tissue$Tissue=="Brain"] <- "brain"
sample_info_imm$data_panel <- "immune"
df <- rbind(sample_info_tissue,sample_info_imm)

df$data_panel <- factor(df$data_panel,
                                    levels = c('epithelial','immune',"brain","blood"))
df$Num_cells_k <- round(df$Num_cells / 1000)


f1c <- plot_stacked_bar(
  df = df,
  x_col = "Tissue",
  y_col = "Num_cells_k",
  fill_col = "data_panel",
  agg_func = sum,
  plot_title = "",
  xlab = "Tissue",
  ylab = "Number of cells (k)",
  fill_legend = "Cell type",
  palette = 'Set3' # Changed color palette
) + theme(legend.position = c(1, 1), # Position relative to entire plot
    legend.justification = c(1, 1)) + # Anchor: 1,1 is top-right
  plot_annotation(
    tag_levels = list(c("C"))
  )
f1c
ggsave(paste0(WORK_DIR,"Figures/Figure1_landscape/C_cellcount.pdf"),width=6,height=4)

```


## F1D Drug type statistics

```{r}
## 1. Count pathway occurrences
df <- as.data.frame(table(drug_info$pathway_name))
colnames(df) <- c("pathway", "count")

## 2. Sort by count descending (clockwise)
df <- df %>%
  arrange(desc(count)) %>%
  mutate(
    pathway = factor(pathway, levels = pathway),
    id = row_number()
  )

## 3. Calculate label angles (prevent inversion)
df <- df %>%
  mutate(
    angle = 90 - 360 * (id - 0.5) / n(),
    hjust = ifelse(angle < -90, 1, 0),
    angle = ifelse(angle < -90, angle + 180, angle)
  )

## 4. Plot radial bar chart
inner_radius <- 6

max_count <- max(df$count)

```

```{r,fig.width=7,fig.height=8}

f1d <- ggplot(df, aes(x = id, y = count)) +
  geom_col(
    width = 1,
    fill = "#4C72B0",      
    color = "white"
  ) +
  
  ## Count labels (near bar tops)
  geom_text(
    aes(
      y = count + 0.6,
      label = count,
      angle = angle,
      hjust = hjust
    ),
    size = 4
  ) +
  
  ## Pathway name labels (outer)
  geom_text(
    aes(
      y = count + 5,     # Push further out
      label = pathway,
      angle = angle,
      hjust = hjust
    ),
    size = 4
  ) +
  
  coord_polar(start = 0) +
  ylim(-inner_radius, max_count + 6) +
  theme_void() +
  theme(
    plot.title = element_text(hjust = 0.5, size = 14)
  ) +
  labs(title = "Number of drugs per pathway") +
  plot_annotation(
    tag_levels = list(c("D"))
  )

f1d
ggsave(paste0(WORK_DIR,"Figures/Figure1_landscape/D_drugcount.pdf"),width=7,height=7)

```





# Heatmap


## F1E Epithelial (sampled hbca)

```{r}
df <- drug_tissuetox_df_ds %>%
  filter(!tissue %in% c("Blood", "Brain"))
value_col = "scPharm_dse_median"
drug_col  = "drug_id_name"
tissue_col = "tissue"
```

```{r}
# Prepare heatmap matrix: rows=tissues, columns=drugs
mat_df <- df %>%
  dplyr::select(
    !!drug_col := all_of(drug_col),
    !!tissue_col := all_of(tissue_col),
    value = all_of(value_col)
  ) %>%
  tidyr::pivot_wider(
    names_from = !!drug_col,
    values_from = value
  )

mat <- as.data.frame(mat_df)
rownames(mat) <- mat[[tissue_col]]
mat[[tissue_col]] <- NULL
mat <- as.matrix(mat)

mat <- mat[rowSums(!is.na(mat)) > 0, , drop = FALSE]
mat <- mat[, colSums(!is.na(mat)) > 0, drop = FALSE]

# Annotation matrix: rows match heatmap columns
rownames(drug_info) <- drug_info$drug_id_name

```


```{r,fig.width=9,fig.height=4.5}
ht <- plot_heatmap_with_annotation(
  mat,
  title_base = "DSE",
  show_column_names = FALSE,
  show_column_dend = FALSE,
  show_row_dend = FALSE,
  row_title = "Tissue",
  column_title = "Drug",
  column_title_side = "bottom",
  col_fun = colorRamp2(
        c(0, 0.3, 0.6),
        c("lightblue", "orange", "red")
      )
) 

draw(
  ht ,
  column_title = "Susceptibility of epithelial cells across normal tissues",
  column_title_gp = grid::gpar(fontsize = 16, fontface = "bold")
) 


pdf(paste0(WORK_DIR,"Figures/Figure1_landscape/E_heatmap_epi.pdf"), width = 9, height = 4.5)

draw(
  ht,
  column_title = "Susceptibility of epithelial cells across normal tissues",
  column_title_gp = grid::gpar(fontsize = 16, fontface = "bold")
)

dev.off()

```


## F1E Immune

```{r}
df=drug_tissuetox_df_imm
value_col = "scPharm_dse_median"
drug_col  = "drug_id_name"
tissue_col = "tissue"
```

```{r}
# Prepare heatmap matrix: rows=tissues, columns=drugs
mat_df <- df %>%
  dplyr::select(
    !!drug_col := all_of(drug_col),
    !!tissue_col := all_of(tissue_col),
    value = all_of(value_col)
  ) %>%
  tidyr::pivot_wider(
    names_from = !!drug_col,
    values_from = value
  )

mat <- as.data.frame(mat_df)
rownames(mat) <- mat[[tissue_col]]
mat[[tissue_col]] <- NULL
mat <- as.matrix(mat)

mat <- mat[rowSums(!is.na(mat)) > 0, , drop = FALSE]
mat <- mat[, colSums(!is.na(mat)) > 0, drop = FALSE]

# Annotation matrix: rows match heatmap columns
rownames(drug_info) <- drug_info$drug_id_name

```


```{r,fig.width=9,fig.height=4.5}
ht <- plot_heatmap_with_annotation(
  mat,
  title_base = "DSE",
  show_column_names = FALSE,
  show_column_dend = FALSE,
  show_row_dend = FALSE,
  row_title = "Tissue",
  column_title = "Drug",
  column_title_side = "bottom",
  col_fun = colorRamp2(
        c(0, 0.3, 0.6),
        c("lightblue", "orange", "red")
      )
)

draw(
  ht,
  column_title = "Susceptibility of immune cells across normal tissues",
  column_title_gp = grid::gpar(fontsize = 16, fontface = "bold")
)


pdf(paste0(WORK_DIR,"Figures/Figure1_landscape/F_heatmap_imm.pdf"), width = 9, height = 4.5)

draw(
  ht,
  column_title = "Susceptibility of immune cells across normal tissues",
  column_title_gp = grid::gpar(fontsize = 16, fontface = "bold")
)

dev.off()
```

## F1G Blood


```{r,fig.width=7,fig.height=4.5}
tissue <- "Blood"

sample_tox_df_subset <- sample_tox_list[[tissue]]

# Prepare plotting matrix
mat_df <- sample_tox_df_subset %>%
  dplyr::select(sample, drug_id_name, DSE) %>%
  pivot_wider(
    names_from = drug_id_name,
    values_from = DSE
  )

mat <- as.data.frame(mat_df)
rownames(mat) <- mat$sample
mat$sample <- NULL

mat <- as.matrix(mat)

ht <- plot_heatmap_with_annotation(
  mat,
  title_base = "DSE",
  show_column_names = FALSE,
  show_row_names = FALSE,
  row_title = "Sample",
  column_title_side = "bottom",
  column_title = "Drug",
  show_column_dend = FALSE,
  show_row_dend = FALSE,
  col_fun = colorRamp2(
        c(0, 0.4, 0.8),
        c("lightblue", "orange", "red")
      )
)

draw(
  ht,
  column_title = "Susceptibility of blood cells across normal samples",
  column_title_gp = grid::gpar(fontsize = 16, fontface = "bold")
)


pdf(paste0(WORK_DIR,"Figures/Figure1_landscape/G_heatmap_blood.pdf"), width = 7, height = 4.5)

draw(
  ht,
  column_title = "Susceptibility of blood cells across normal samples",
  column_title_gp = grid::gpar(fontsize = 16, fontface = "bold")
)

dev.off()


```



## F1H Brain 


```{r,fig.width=7,fig.height=4.5}
tissue <- "Brain"

sample_tox_df_subset <- sample_tox_list[[tissue]]

# Prepare plotting matrix
mat_df <- sample_tox_df_subset %>%
  dplyr::select(sample, drug_id_name, DSE) %>%
  pivot_wider(
    names_from = drug_id_name,
    values_from = DSE
  )

mat <- as.data.frame(mat_df)
rownames(mat) <- mat$sample
mat$sample <- NULL

mat <- as.matrix(mat)

ht <- plot_heatmap_with_annotation(
  mat,
  title_base = "DSE",
  show_column_names = FALSE,
  show_row_names = FALSE,
  row_title = "Sample",
  column_title_side = "bottom",
  column_title = "Drug",
  show_column_dend = FALSE,
  show_row_dend = FALSE,
  col_fun = colorRamp2(
        c(0, 0.4, 0.8),
        c("lightblue", "orange", "red")
      )
)

draw(
  ht,
  column_title = "Susceptibility of brain cells across normal samples",
  column_title_gp = grid::gpar(fontsize = 16, fontface = "bold")
)


pdf(paste0(WORK_DIR,"Figures/Figure1_landscape/H_heatmap_brain.pdf"), width = 7, height = 4.5)

draw(
  ht,
  column_title = "Susceptibility of brain cells across normal samples",
  column_title_gp = grid::gpar(fontsize = 16, fontface = "bold")
)

dev.off()


```


